[project]
name = 'Property-Rights-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.licensing-agreement]
path = 'contracts/licensing-agreement.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-nft]
path = 'contracts/research-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-registry]
path = 'contracts/research-registry.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
